#pragma once

#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM_SHORT 125
#define TAPPING_TERM 150
#define TAPPING_TERM_LONG 225
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
